### ISSUE TITLE
Missing something to work with NPM instead of Caddy

### ISSUE THREAD

**Issue by thibmart1** [rcaillon-Iliad/send-caddy-authelia#2]
Hi @rcaillon-Iliad, I wonder if you could help me with my setup, it is pretty similar as yours unless it uses [NPM](https://nginxproxymanager.com/setup/) instead of Caddy.

I followed [authelia's instructions](https://www.authelia.com/integration/proxies/nginx-proxy-manager/) to setup authentication on Send (with snippets and all) and I added some config to the authelia `configuration.yml` file for the uploading-only-authentication part

Unfortunately when I try to upload from the GUI it gets stuck at 0% percent and don't upload anything. I have a 404 error from the `wss://dock.boardthenautilus.com/api/ws` GET request with a `NS_ERROR_WEBSOCKET_CONNECTION_REFUSED`.

I think I might have missed something in my authelia / nginx config but I don't know what.
Besides, when I remove authelia's authentication from my Send config on NPM it works prety well.

My NPM config :
```
include /snippets/authelia-location.conf;

location / {
    include /snippets/proxy.conf;
    include /snippets/authelia-authrequest.conf;
    proxy_pass $forward_scheme://$server:$port;
}
```

My authelia custom config :
```
access_control:
  default_policy: deny
  rules:
    # specific config for send
    - domain: "send.mydomain.com"
      policy: bypass
      resources:
        - "^(/api)?/download/.*$"
        - "^/api/metadata/.*$"
        - ".(js|css|jpg|png|svg|woff2|txt)$"
    - domain: "send.mydomain.com"
      policy: one_factor
```
